### ISSUE TITLE
Documentation for templates

### ISSUE THREAD

**Issue by J05HI** [ViRb3/apk-utilities#1]
Hello @ViRb3,

do you have a documentation for working with the templates? For example how to log variables in methods to logcat? Is this even possible with Frida? 
Thank you very much!

**Comment by ViRb3** [comment]
Hey there,

The templates are just snippets of code I find myself using often, I don't plan to document them for now. As for Frida, I'd recommend reading the official documentation: https://frida.re/docs/home/. There are plenty of Frida scripts available here: https://codeshare.frida.re/ and https://github.com/iddoeldor/frida-snippets

**Comment by J05HI** [comment]
Awesome!
Thank you so much for your help!
